name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Ruff
        run: |
          ruff check .
          ruff format --check .

      - name: Lint with Pylint
        run: |
          pylint main.py tree_planner/

      - name: Run tests with coverage
        run: |
          pytest --cov=tree_planner --cov-report=term-missing --cov-fail-under=80 -v

      - name: Upload coverage reports
        if: matrix.python-version == '3.13'
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
